a = float(input("Digite un valor para a: "))
b = float(input("Digite un valor para b: "))
c = float(input("Digite un valor para c: "))
resultado = (a ** 3 * (b ** 2 - 2 * a * c)) / (2 * b)
print(f"El resultado es {resultado}")